apiVersion: v1
kind: Service
metadata:
  name: salman
  labels:
    app: salman
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30036
    targetPort: 80
    protocol: TCP
  selector:
    app: salman

